# run with: docker compose -f docker_compose.yaml up
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

# you can specify that your script is runnable
# only if the db is up / healthy -- need to adjust your ports (?) and app.py name (?)
#  web:
#    build: .
#    ports:
#      - "80:8000"
#    depends_on:
#      db:
#        condition: service_healthy
#    command: [ "python", "app.py" ]